// Monster Hunter World: Iceborne — Monster Data
const MONSTERS = [
  {
    id: 1,
    name: "Velkhana",
    title: "Elder Dragon of Ice",
    monsterType: "Elder Dragon",
    habitat: "Hoarfrost Reach",
    size: "Large",
    description: "An elder dragon with the power to freeze all in its path. It can spread cold air from its breath and freeze moisture in the air to create walls of ice and icy armor for itself.",
    lore: "The cold that bites without wind, the ice that forms without water — these are the signs that Velkhana walks the land.",
    weaknesses: ["Fire", "Thunder"],
    resistances: ["Ice", "Water"],
    elements: ["Ice"],
    imageUrl: "https://placehold.co/480x360/0d1a2e/6ab0d4?text=Velkhana",
    featured: true,
    sortOrder: 1
  },
  {
    id: 2,
    name: "Brachydios",
    title: "Explosive Scale Wyvern",
    monsterType: "Brute Wyvern",
    habitat: "Elder's Recess",
    size: "Large",
    description: "A brute wyvern that uses a unique slime mold to create powerful explosions. Its forearms are coated in this explosive slime, which it uses to devastating effect in combat.",
    lore: "Where the ground turns green and the air smells of sulfur, Brachydios has marked its territory with explosive intent.",
    weaknesses: ["Ice", "Water"],
    resistances: ["Fire", "Thunder"],
    elements: ["Blast"],
    imageUrl: "https://placehold.co/480x360/1a1a0d/c9a227?text=Brachydios",
    featured: true,
    sortOrder: 2
  },
  {
    id: 3,
    name: "Glavenus",
    title: "Tail Blade Wyvern",
    monsterType: "Brute Wyvern",
    habitat: "Wildspire Waste",
    size: "Large",
    description: "A brute wyvern known for its massive, blade-like tail. It can sharpen this tail by grinding it against its teeth, and uses fire breath to superheat it for devastating attacks.",
    lore: "The blade that cleaves the sky — Glavenus is both sword and wielder, a creature that has mastered the art of the slash.",
    weaknesses: ["Water", "Ice"],
    resistances: ["Fire"],
    elements: ["Fire"],
    imageUrl: "https://placehold.co/480x360/1a0d0d/e05c3a?text=Glavenus",
    featured: true,
    sortOrder: 3
  },
  {
    id: 4,
    name: "Barioth",
    title: "Snow Wyvern",
    monsterType: "Flying Wyvern",
    habitat: "Hoarfrost Reach",
    size: "Large",
    description: "A flying wyvern that inhabits frozen tundra regions. Its large tusks and claws allow it to traverse icy terrain with ease, and it can generate powerful blizzard-like winds.",
    lore: "Swift as the arctic wind, Barioth is a predator perfectly adapted to the frozen wastes it calls home.",
    weaknesses: ["Fire", "Thunder"],
    resistances: ["Ice"],
    elements: ["Ice"],
    imageUrl: "https://placehold.co/480x360/0d1a2e/80deea?text=Barioth",
    featured: false,
    sortOrder: 4
  },
  {
    id: 5,
    name: "Nargacuga",
    title: "Swift Wyvern",
    monsterType: "Flying Wyvern",
    habitat: "Ancient Forest",
    size: "Large",
    description: "A flying wyvern known for its incredible speed and agility. Its black fur and sleek body allow it to move with lightning-fast precision, making it a formidable predator.",
    lore: "A shadow that moves like water, Nargacuga strikes before its prey even knows it has been hunted.",
    weaknesses: ["Thunder", "Fire"],
    resistances: ["Water"],
    elements: [],
    imageUrl: "https://placehold.co/480x360/0d0d0d/888888?text=Nargacuga",
    featured: false,
    sortOrder: 5
  },
  {
    id: 6,
    name: "Tigrex",
    title: "Roaring Wyvern",
    monsterType: "Flying Wyvern",
    habitat: "Wildspire Waste",
    size: "Large",
    description: "An ancient flying wyvern whose powerful roar can shatter boulders. It is considered a primitive species that relies on brute force and overwhelming aggression.",
    lore: "From the age before hunters, Tigrex has roared its dominance across every land it has claimed.",
    weaknesses: ["Thunder", "Ice"],
    resistances: [],
    elements: [],
    imageUrl: "https://placehold.co/480x360/1a1208/c9a227?text=Tigrex",
    featured: false,
    sortOrder: 6
  },
  {
    id: 7,
    name: "Zinogre",
    title: "Thunder Wolf Wyvern",
    monsterType: "Fanged Wyvern",
    habitat: "Ancient Forest",
    size: "Large",
    description: "A fanged wyvern that can harness the power of thunder by charging up its body with lightning bugs called Thunderbugs. When fully charged, it becomes an electrifying force of nature.",
    lore: "The storm given form — Zinogre is a creature that has made lightning its own, wearing it like armor and wielding it like a weapon.",
    weaknesses: ["Ice", "Water"],
    resistances: ["Thunder"],
    elements: ["Thunder"],
    imageUrl: "https://placehold.co/480x360/0d1a0d/ffd740?text=Zinogre",
    featured: false,
    sortOrder: 7
  },
  {
    id: 8,
    name: "Namielle",
    title: "Abyssal Elder Dragon",
    monsterType: "Elder Dragon",
    habitat: "Coral Highlands",
    size: "Large",
    description: "An elder dragon that controls both water and thunder. Its beautiful bioluminescent body conceals tremendous power, and it can create powerful electrical discharges through water.",
    lore: "From the deepest waters where light never reaches, Namielle rises — a creature of both terrible beauty and devastating power.",
    weaknesses: ["Fire"],
    resistances: ["Water", "Thunder", "Ice"],
    elements: ["Water", "Thunder"],
    imageUrl: "https://placehold.co/480x360/0d0d1a/29b6f6?text=Namielle",
    featured: false,
    sortOrder: 8
  },
  {
    id: 9,
    name: "Shara Ishvalda",
    title: "Destroyer of Mountains",
    monsterType: "Elder Dragon",
    habitat: "Guiding Lands",
    size: "Large",
    description: "An elder dragon that uses vibrations to manipulate sand and earth. It can reshape the terrain around it, and its true form is revealed only after shedding its rocky exterior.",
    lore: "The earth itself trembles at its passage — Shara Ishvalda does not merely inhabit the land, it commands it.",
    weaknesses: ["Water", "Ice"],
    resistances: ["Fire"],
    elements: ["Dragon"],
    imageUrl: "https://placehold.co/480x360/1a0d0d/ce93d8?text=Shara+Ishvalda",
    featured: false,
    sortOrder: 9
  },
  {
    id: 10,
    name: "Rajang",
    title: "Violent Ape",
    monsterType: "Fanged Beast",
    habitat: "Hoarfrost Reach",
    size: "Large",
    description: "A powerful fanged beast that can absorb the horns of Kirin to gain lightning powers. In its enraged state, its fur turns golden and its strength increases dramatically.",
    lore: "There are few creatures in the known world that inspire the same primal fear as Rajang — a beast that has mastered both thunder and fury.",
    weaknesses: ["Ice"],
    resistances: ["Thunder", "Fire"],
    elements: ["Thunder"],
    imageUrl: "https://placehold.co/480x360/1a1208/ffd740?text=Rajang",
    featured: false,
    sortOrder: 10
  },
  {
    id: 11,
    name: "Savage Deviljho",
    title: "Invading Tyrant",
    monsterType: "Brute Wyvern",
    habitat: "Ancient Forest",
    size: "Large",
    description: "A variant of Deviljho that has become so consumed by hunger that it has entered a perpetual state of rage. Its body has turned a deep crimson, and its power has increased tremendously.",
    lore: "When Deviljho has consumed everything in its territory and still hungers, it becomes Savage Deviljho — a creature that exists only to destroy.",
    weaknesses: ["Thunder", "Dragon"],
    resistances: ["Fire"],
    elements: ["Dragon"],
    imageUrl: "https://placehold.co/480x360/1a0808/e05c3a?text=Savage+Deviljho",
    featured: false,
    sortOrder: 11
  },
  {
    id: 12,
    name: "Fulgur Anjanath",
    title: "Thunder Fang Wyvern",
    monsterType: "Bird Wyvern",
    habitat: "Ancient Forest",
    size: "Large",
    description: "A subspecies of Anjanath that has adapted to use thunder instead of fire. Its pale blue coloration and electrical abilities make it a distinct and dangerous variant.",
    lore: "Where the original Anjanath breathes fire, Fulgur Anjanath crackles with lightning — a testament to nature's endless capacity for variation.",
    weaknesses: ["Water", "Ice"],
    resistances: ["Thunder"],
    elements: ["Thunder"],
    imageUrl: "https://placehold.co/480x360/0d1a1a/6ab0d4?text=Fulgur+Anjanath",
    featured: false,
    sortOrder: 12
  }
];

const HABITATS = [...new Set(MONSTERS.map(m => m.habitat))];
const MONSTER_TYPES = [...new Set(MONSTERS.map(m => m.monsterType))];